# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - assetorbit-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_PACKAGE_PATH: 'packages/backend'
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          npm ci --ignore-scripts

      - name: Generate Prisma Client
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          npx prisma generate

      - name: Build backend
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          npx tsc -p tsconfig.prod.json

      - name: Remove dev dependencies
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          npm prune --production

      - name: Copy package files
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          cp package*.json dist/

      - name: Zip artifact for deployment
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/dist
          zip -r ${{ github.workspace }}/release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read 

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A228BD82482B46E4BF47BB41B32528F9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3FB316A6408240F5B79F326BBB00DCDD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F12703DB9BE043F8988F14043FFDDF35 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'assetorbit-api'
          slot-name: 'Production'
          package: . 