# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js backend to Azure Web App - assetorbit-api

# Prevent overlapping deployments
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read # required for actions/checkout
      id-token: write # required for azure/login

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      # Install all workspace dependencies
      - name: Install dependencies (root)
        run: npm ci

      # Build only the backend workspace
      - name: Build backend workspace
        run: npm run build --workspace @ats/backend

      # Generate Prisma client
      - name: Generate Prisma client
        run: |
          cd packages/backend
          npx prisma generate

      # Create deployment package with backend code and dependencies
      - name: Create deployment package
        run: |
          mkdir -p deploy
          cp -r packages/backend/dist deploy/
          cp -r packages/backend/generated deploy/
          cp packages/backend/package.json deploy/
          cd deploy
          # Install only production dependencies directly
          npm install express cors morgan helmet dotenv @prisma/client @azure/identity @microsoft/microsoft-graph-client csv-writer exceljs passport passport-azure-ad pino pino-pretty prisma --production

      # Log in to Azure using federated credentials
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A228BD82482B46E4BF47BB41B32528F9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3FB316A6408240F5B79F326BBB00DCDD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F12703DB9BE043F8988F14043FFDDF35 }}

      # Deploy the deployment package
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'assetorbit-api'
          slot-name: 'Production'
          package: deploy 
